---
- name: A playbook with variables
  hosts: linuxhosts
  vars: 
  - var1: zig
  - var2: zag
  tasks: 
  - name: print data
    shell: echo "{{var1}} when you should {{var2}}" > /home/ennil/Desktop/vars.txt
